{% set name = "pyquicksetup" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyquicksetup-{{ version }}.tar.gz
  sha256: 9c987845725ac1f7c155363bf35440faf733e49af2f96e4de48567870b8578b1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - setuptools

test:
  imports:
    - pyquicksetup
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.xavierdupre.fr/app/pyquickhelper/helpsphinx/index.html
  summary: Predefined setup commands relying on pyquickhelper.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xhochy
